### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ghost** [Diego-Linux/Full-authentication-vanillaJS-localStorage#1]

**Comment by Diego-Linux** [comment]
Não usei banco de dados, somente localStorage.

**Comment by ghost** [comment]
Mas caso eu queria colocar por onde começo?

Em qui, 13 de jan de 2022 09:01, Diego ***@***.***> escreveu:

**Comment by Diego-Linux** [comment]
Bom, ai eu recomendaria outros projetos.
Este projeto é somente Javascript puro e o foco é salvar os items em localStorage.
Caso você queira projetos com banco de dados e também se aprofundar mais sobre o assunto, eu te recomendaria o MongoDB com NodeJS.
Canais do youtube que recomendo: Rocketseat, O irmão mais velho, Victor Lima - Guia do Programador.
Abçs.
